### ISSUE TITLE
Basic gutter renderer for code folding

### ISSUE THREAD

**Issue by swilmet** [swilmet/gtef#1]
See:
https://wiki.gnome.org/Projects/GtkSourceView/CodeFolding

This issue is for the GutterRendererFolds class, I think it's a good first step.

**Comment by NoreSoft** [comment]
I had some more time today to work on the code folding. I added the classes GtefFolding and GtefGutterRendererFolding in my branch. The test actually looks quite nice. I hope I will find some more time soon.

**Comment by swilmet** [comment]
Cool!

It would be great to have the GutterRendererFolds class in Gtef. Even if in the end the class is not intended to be public, it can be public in Gtef initially and we can make it private at a later version. It would have the advantage to have at least "something".

**Comment by swilmet** [comment]
Early comments about the GutterRendererFolds:

- the filenames should be gtef-gutter-renderer-folds.*, with more dashes. GtkSourceView has a different convention.
- instead of GtefGutterRendererFoldsFoldingState, the enum type can be named GtefGutterRendererFoldsState.
- instead of clear_folding_states() and add_folding_state(), there should be instead a function set_state(). See how gtksourcegutterrenderertext.h and gtksourcegutterrendererlines.h works. The latter is a subclass of the former. The same way as GutterRendererFolding should be a subclass of GutterRendererFolds (but as a first step let's focus only about GutterRendererFolds, with a basic test).

I didn't look at the *.c file yet.

**Comment by NoreSoft** [comment]
Thanks for the comments!

I changed the filenames and the enum type name.

With the other thing I'm not quite sure. The reason for this two functions instead of a setter is that the class stores the folding state for every line inside a Hash-Table. So the child class is calling clear_folding_state() to clear this table and add_folding_state() to add a folding state for one single line. Lines not added this way are considered as FOLDING_NONE. So this way the child class can calculate which line has which folding state without handling the Hash Table directly. I found this more convenient and less error-prone, because the object is not transfered.
Maybe the naming does not reflect this too well. What do you think about that approach?

**Comment by swilmet** [comment]
The GutterRendererFolding should call gutter_renderer_folds_set_state() on each draw (i.e. for each cell that needs to be drawn). See the class description of GtkSourceGutterRenderer.

The state is stored in GtefFolding. The GutterRendererFolding should ask to GtefFolding the folding state at a certain place, to tell the GutterRendererFolds to draw that state for that cell. GutterRendererFolds should not store the states, it's a dumb class that does only the drawing, cell by cell.

You can see how it works in the available gutter renderers in GtkSourceView.

**Comment by NoreSoft** [comment]
OK, I'll have a look at it.

**Comment by NoreSoft** [comment]
So, now the folding state is only set for the current line by GtefGutterRendererFolding. I did this in the draw method before calling the parents class draw method. Is that right?

Yours
  David

**Comment by swilmet** [comment]
Yes, it seems right.

By looking at the *.c file, there are many small details (for the coding style) that are not correct or are missing. So what I would suggest now, is to:
- create a new branch with only the GutterRendererFolds class, coming with a working test program (the test program needs a dumb GutterRendererFolds subclass that hardcodes some state for certain line numbers, like I did initially in GutterRendererFolds, but now it needs to be external).
- the new branch needs to have a clean history (e.g. only one commit).
- it's better if it comes with well-formatted GTK-Doc documentation (see if the output is correct in the html pages).
- then do a pull request, and I'll review the commit.

**Comment by swilmet** [comment]
Done!

**Comment by swilmet** [comment]
I've opened a new issue for a next possible step:
https://github.com/swilmet/gtef/issues/3

**Comment by swilmet** [comment]
Btw, David, I've added you to the roadmap:
https://wiki.gnome.org/Projects/GtkSourceView/RoadMap

**Comment by NoreSoft** [comment]
Ok, thank you.
