### ISSUE TITLE
GtefFoldRegion

### ISSUE THREAD

**Issue by swilmet** [swilmet/gtef#3]
The next step for code folding is GtefFoldRegion.

https://wiki.gnome.org/Projects/GtkSourceView/CodeFolding

No need to implement the uncertain things (marked with '?' on the wiki page) for a first iteration. We'll figure out later what is really needed.

I can expand my API thoughts, to give more details, if needed.

When folding the region, the first line should still be visible. I think the API can assume that the fold region starts at the beginning of a line and ends at the end of a line (i.e. it is not possible to fold only the middle of a line, for example, this would not be very useful, and would not fit with GutterRendererFolds). So I think when applying the tag, it should start at the following line, not the line given by the start GtkTextIter. The class should document this behavior.

**Comment by NoreSoft** [comment]
In my first proposal in my code-folding branch I realized the attributes as Object properties. There is no fold()/unfold() at the moment, since it can be done by g_object_set_property(). Is it still a good idea to have a fold() and unfold() method? Is it better to access the attributes directly in these or to call g_object_set_property() instead?

Also, the _new() method takes GtkTextIters as argument, but the class stores GtkTextMarks (because GtkTextIters are not guaranteed to stay valid), so the conversion is in the _new() method. I also read that there generally should be no code in the _new() method, but I am not sure if this also applies to such basic stuff like converting a GtkTextIter to a GtkTextMark. What do you think and how to solve this? Maybe the _new() method should only accept GtkTextMark, but on the other hand I would not like the caller to care for the conversion, nor the gravity.

When I wrote the class three weeks ago, i wrote it down how it came to my mind. So maybe I should go through it again and see if some parts need to be rewritten, or to keep it more close to your API proposal. Also I am not sure about the weak pointers I used. But if you already want to look at it and have some comments for me, that would be helpful of course.

Link to my code-folding tree: https://github.com/NoreSoft/gtef/tree/code-folding

**Comment by swilmet** [comment]
The new() function should ideally just do g_object_new() and pass properties values. Sometimes the developer is lazy and doesn't add properties, and do some initialization in new(), after g_object_new() (this is ok for private classes). But for example if a widget is created with GtkBuilder, GtkBuilder will call g_object_new() with the widget type, not the new() function, so calling g_object_new() externally to the class needs to work too (this can be used for language bindings too).

So here, you can create a 'start' and 'end' construct-only properties of type GtkTextIter. Internally, I'm not sure if it is better to use a GtkTextTag directly, or use two GtkTextMarks and apply a GtkTextTag only when the region is folded. It is better to do a simple implementation first, and if performance becomes a problem it can be fixed later.

When creating properties, it is better to add get/set functions (here only get() is public, because the properties can be set only at construction time, there can be set_start()/set_end() static functions), and call the get/set functions in get_property()/set_property(). The conversion between GtkTextIter and GtkTextMark should be done by the get/set functions. For the set*() and new() functions, the GtkTextIter parameter can be const (of type `const GtkTextIter *iter`), to show that the function doesn't modify the iter.

When using weak pointers, it is important to get the code right, because if the weak pointer is not removed correctly, NULL can be set at a random place in memory, which can be evil to debug if it doesn't happen often. There are examples of weak pointers in GtkSourceView code (and Gtef too now).

**Comment by swilmet** [comment]
And instead of fold()/unfold(), it can be set_folded(bool) (and get_folded()).

**Comment by swilmet** [comment]
Updated wiki page.

**Comment by NoreSoft** [comment]
By now, the start and end object property are only writable. There is a get_start() and get_end() method, but with the object property I don't know how to do it. I think, we would have to allocate a GtkTextIter, return the pointer to it and let the caller of g_object_get() free the memory again. With a normal object type this would be the normal behaviour I think, but with a GtkTextIter it seems unclean and error-prone to me. What do you think?

There is also a text-buffer property. But I did not write a set_buffer() method, since it would have been very short and only called from set_property during the object construction.

I wanted to ask you about the weak pointer to the GtkTextBuffer again. Do we need it at all here? Because in the end I think the GtefFolding and thereby the GtefFoldRegions will be part of the buffer and therefore cleaned up by the buffer automatically when it is destroyed.

**Comment by swilmet** [comment]
With a pull request it would be easier for me to comment on the code.

You can use `g_param_spec_boxed()` and `g_value_<something>_boxed()` for the GtkTextIter properties.

For the weak ref, when removing it you need to check if it is not already NULL. And everywhere in the code, before using priv->buffer, you need to check if it is not NULL (I didn't check if it was correctly done already).

The GtkTextBuffer property can be named "buffer", that's the name used in the FileLoader and FileSaver, for example.

Instead of gtef_fold_region_constructor(), you can create the tag in a set_buffer() static function, at the same time than the buffer is set.

**Comment by swilmet** [comment]
Or, better, you can create the tag only when needed, i.e. when folding the region. On unfolding, you can remove and destroy the tag.

**Comment by swilmet** [comment]
Actually, I don't think a property is really useful, because the notify signal is probably not needed.

It's simpler with:
- new(start, end);
- set_bounds(start, end);
- get_bounds(start, end);
- no properties for start/end.

The new() function can call set_bounds() after the call to g_object_new(). The code will be simpler, and the API can anyway be changed in the future if needed.

Sorry for the noise. (API design is hard, there are many possibilities…).

**Comment by NoreSoft** [comment]
I created a pull request now.

Is it OK to just return FALSE in get_folded() if the self parameter is no GtefFoldRegion?

**Comment by swilmet** [comment]
Yes the g_return_val_ calls should return sensible values, usually the default value. By default the text is not folded, it is visible.

**Comment by swilmet** [comment]
So, almost done, still some FIXMEs to fix.

**Comment by NoreSoft** [comment]
In the FIXME in test-fold-region.c you wrote "Use gtk_text_iter functions to see if the invisible region is correctly skipped." but I think gtk_text_iter functions don't care about invisible tags. Or maybe I don't fully understand what you mean.

**Comment by swilmet** [comment]
The unit test can call for example `gtk_text_iter_forward_visible_line()`.

**Comment by NoreSoft** [comment]
While writing the unit test, the following occurred:
In one test I unref the buffer of the fold region and afterwards call GtefFoldRegion's methods on that fold region. Thus I noticed that set_bounds() crashes if invalid GtkTextIters are passed. Is there any way of testing if GtkTextIters are valid, e.g. if there buffer still exists, has changed or if they are initialized at all?

**Comment by swilmet** [comment]
It is a programming error if set_bounds() is called when the buffer is freed.

set_bounds() cannot really check if the iters are valid, but it can check if the buffer is NULL.

**Comment by NoreSoft** [comment]
> It is a programming error if set_bounds() is called when the buffer is freed.
>
> set_bounds() cannot really check if the iters are valid, but it can check if the buffer is NULL.

I opened a pull request to check first if buffer is NULL and afterwards check the lines. The other way around it did not make sense, because without a valid buffer Iters would always be invalid and the program would crash.

**Comment by NoreSoft** [comment]
I created another pull request for the unittest. It may be a little bit detailed, but in my opinion for a unittest it is better to have too much then too less test cases.

Btw: The test fails with the current master, but after merging the other two pull requests, it works.

**Comment by swilmet** [comment]
For the unit tests, it is not a good idea to test "too much", because you test things that are not guaranteed by the GTK+/GtkSourceView APIs.

**Comment by NoreSoft** [comment]
In a new Fixme you write 

> rename [...] and when start/end are * GtkTextIters: start_iter, end_iter.

In set_bounds() there are parameters start and end, but we cannot use them directly because they are const and we use gtk_text_iter_forward_line() to modify them. So there are already additional variables start_iter and end_iter. What naming would you suggest here?

**Comment by swilmet** [comment]
The `gtk_text_iter_forward_line()` will be inside the `apply_tag()` function.

Otherwise, a possible naming is "my_start_iter". Or sometimes the function parameter is prefixed with an underscore.

**Comment by NoreSoft** [comment]
While fixing the FIXMEs I saw that set_folded()p does not check if the bounds are already set either, so I fixed it. I think maybe I could add some unit test, that calls some methods before setting the bounds. What do you think?

**Comment by swilmet** [comment]
Yes, it's always a good idea to add unit tests. Usually I don't write unit tests for all that stuff myself, but why not. As a general rule, it is not really needed to test trivial functions like getters and setters. It is better to focus the unit tests on the important/more complicated things.

So FoldRegion is almost done! thanks for your work.

**Comment by swilmet** [comment]
For the gravities of the GtkTextMarks, I think start_mark can have left gravity, and end_mark right gravity. start_mark is typically at the beginning of a line, so it's better to keep it at the beginning of the line if text is inserted there. And end_mark can be at the end of a line.

Anyway, on text insertion/deletion, the GtefFolding tree can be adapted (by the parser). So GtefFoldRegions can be created/destroyed/modified.

**Comment by swilmet** [comment]
I've changed the gravities of the GtkTextMarks. And I've released Gtef 1.0.

Although GtefFoldRegion could be better documented, it can be done later.

So the next step is more complicated, it's the GtefFolding tree. I've opened a new issue for that:
https://github.com/swilmet/gtef/issues/12

**Comment by NoreSoft** [comment]
Hi Sebastién,

On 29.10.2016 13:44, Sébastien Wilmet wrote:
> I've changed the gravities of the GtkTextMarks. And I've released Gtef 1.0.
> 
> Although GtefFoldRegion could be better documented, it can be done later.
> 
> So the next step is more complicated, it's the GtefFolding tree. I've opened a new issue for that:
> https://github.com/swilmet/gtef/issues/12
> 

Thanks for doing this. I was very busy the last weeks because of a new
job. Sorry for not answering. But I still want to work on this. :-)
Hopefully I will find some time this weekend.

David

**Comment by swilmet** [comment]
Cool, good to hear, I'm looking forward to your patches, but no hurry, take your time ;)
